const WALLET_CONNECT_PROJECT_ID = process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID!;
const ETH_SEPOLLIA_RPC = process.env.NEXT_PUBLIC_ETHEREUM_SEPOLLIA_RPC_URL!;

export {
    WALLET_CONNECT_PROJECT_ID,
    ETH_SEPOLLIA_RPC
}